### PR TITLE
Fix webpack error: the request of a dependency is an expression

### LINKED ISSUE #7: warning  in ./node_modules/node-gyp-build/index.js
WARNING  Compiled with 2 warnings                                      11:32:56

 warning  in ./node_modules/node-gyp-build/index.js

13:9-32 Critical dependency: the request of a dependency is an expression

 warning  in ./node_modules/node-gyp-build/index.js

20:15-54 Critical dependency: the request of a dependency is an expression

### PR DESCRIPTION
**Pull request by 0xh0b0**
fixes #7

### CODE REVIEW

File: index.js [hunk 1]
```diff
@@ -2,6 +2,8 @@ var fs = require('fs')
 var path = require('path')
 var os = require('os')
 
+var runtimeRequire = typeof __webpack_require__ === 'function' ? __non_webpack_require__ : require
```
Comment (mafintosh) [inline index.js]: mind adding a comment that this is to make it work on webpack?

**Comment by mafintosh** [comment]
3.5.1 - Thanks!
